[package]
name = "cub_diff_lib_gtk"
version = "0.1.0"
authors = ["Peter Williams <pwil3058@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
regex = "0.2"

cub_diff_lib = { path = "../cub_diff_lib"}
pw_gix = { git = "https://github.com/pwil3058/rs_pw_gix.git" }
